import "./index.css";
import { Composition, Still } from "remotion";
import { MyComposition } from "./Composition";
import { CloseTabs } from "./CloseTabs";
import {
  GuideToBeingLessAvailable,
  TOTAL_DURATION_IN_FRAMES,
} from "./GuideToBeingLessAvailable";
import {
  PancracioQuote,
  defaultPancracioQuoteProps,
  POST_WIDTH,
  POST_HEIGHT,
} from "./PancracioQuote";

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="MyComp"
        component={MyComposition}
        durationInFrames={90}
        fps={30}
        width={1280}
        height={720}
      />
      <Composition
        id="CloseTabs"
        component={CloseTabs}
        durationInFrames={600}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="GuideToBeingLessAvailable"
        component={GuideToBeingLessAvailable}
        durationInFrames={TOTAL_DURATION_IN_FRAMES}
        fps={30}
        width={1080}
        height={1920}
      />
      {/* Daily Instagram quote card. Text is composited here, not generated by GPT-4o —
          see PancracioQuote.tsx for why. Render with:
          npx remotion still PancracioQuote out.png --props=props.json */}
      <Still
        id="PancracioQuote"
        component={PancracioQuote}
        width={POST_WIDTH}
        height={POST_HEIGHT}
        defaultProps={defaultPancracioQuoteProps}
      />
    </>
  );
};
